Fix missing errno.h header
Fixes this compile error:

```
../src/cc/frontends/clang/kbuild_helper.h:40:64: error: use of undeclared identifier 'errno'
      fprintf(stderr, "chdir(%s): %s\n", dst.c_str(), strerror(errno));
```